server:
    port: 59527

#db
spring:
    messages:
        basename: i18n.messages
        cache-duration: 3600
        encoding: UTF-8
#network
network:
    url:
        #connection: html/connection.html
        #activating: html/activating.html
        landing: html/login.html
        test: html/test_upload.html

path:
    data: /data/

#log
logging:
    path: ./logs/
    file:
        max-size: 30MB
        max-history: 3

