server:
    port: 8081

#db
spring:
    datasource:
        driver-class-name:
#network
network:
    url:
        connection: html/connection.html
        activating: html/activating.html
        landing: html/landing.html

path:
    data: /data/

#log
logging:
    path: ./logs/
    file:
        max-size: 30MB
        max-history: 3
