server:
    port: 8081
#network
network:
    url:
        init: /static/html/init.html
        connection: /static/html/connection.html
        activating: /static/html/activating.html
        landing: /static/html/landing.html

#log
logging:
    path: ../logs
    file:
        max-size: 60MB
        max-history: 3